#pragma once
#define SCORE_VALUE_GOOMBA		100
#define SCORE_VALUE_KOOPA		100
#define SCORE_VALUE_COIN		100
#define SCORE_VALUE_MUSHROOM	1000
#define SCORE_VALUE_LEAF		1000
#define SCORE_VALUE_PIRANHA		100